title: Pythonic code
author: Kavin Thiruvalluvan
email: kavinthiru93@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Implementation of pythonic code based on the LinkedIn Learning course

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  Kavint9

show_excerpts: true # set to false to remove excerpts on the homepage
